version: '3.8'

services:
  airflow-scheduler:
    build: .
    restart: on-failure
    volumes:
      - .:${AIRFLOW_DATAOPS_PATH}
      - airflow-logs:${AIRFLOW_HOME}/logs
    entrypoint: sh /docker-entry.sh
    working_dir: ${AIRFLOW_DATAOPS_PATH}
    links:
      - airflow-db
      - lake
    depends_on:
      - airflow-db
      - lake
    env_file: .env
    environment:
      PYTHONWARNINGS: ignore:Unverified HTTPS request
    # ports:
    #   - 8793:8793

  airflow-webserver:
    build: .
    command: bash -c "echo \"AUTH_ROLE_PUBLIC='Admin'\" > $AIRFLOW_HOME/webserver_config.py && airflow webserver -p 8080"
    restart: on-failure
    depends_on:
      - airflow-db
      - airflow-scheduler
    links:
      - airflow-db
    env_file: .env
    volumes:
      - .:${AIRFLOW_DATAOPS_PATH}
      - airflow-logs:${AIRFLOW_HOME}/logs
    ports:
      - 8080:8080

  airflow-db:
    image: postgres:10.9
    restart: always
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
    ports:
      - 5432:5432

  lake:
    image: postgres:11.10
    restart: always
    environment:
      POSTGRES_USER: lake
      POSTGRES_PASSWORD: lake
    volumes:
      - ./.docker/lake:/docker-entrypoint-initdb.d
    ports:
      - 5433:5432
  
  mysql:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_PASSWORD=root
      - MYSQL_DATABASE=mydb
    ports:
      - "3306:3306"
    volumes:
      - ./.docker/mysql:/var/lib/mysql

volumes:
  airflow-logs: 
